### ISSUE TITLE
README.playground Errors

### ISSUE THREAD

**Issue by perlguy99** [devlucky/Kakapo#102]
I'm having problems running the playground file.

I am on Xcode 7.3.1 and downloaded your latest source.  I compiled the iOS scheme to get the import working in the playground.  But, once I did that, I got a bunch of other errors...

I'm not sure exactly how to fix this for the playground and was hoping that you could help.

Thanks!

Errors I am getting:

Playground execution failed: README.playground:3:16: error: use of undeclared type 'Serializable'
struct Parrot: Serializable {
               ^~~~~~~~~~~~
README.playground:13:13: error: use of undeclared type 'Serializable'
struct Zoo: Serializable {
            ^~~~~~~~~~~~
README.playground:21:19: error: use of undeclared type 'CustomSerializable'
struct CustomZoo: CustomSerializable {
                  ^~~~~~~~~~~~~~~~~~
README.playground:26:42: error: use of undeclared type 'KeyTransformer'
    func customSerialize(keyTransformer: KeyTransformer?) -> AnyObject? {
                                         ^~~~~~~~~~~~~~
README.playground:41:13: error: use of undeclared type 'JSONAPIEntity'
struct Dog: JSONAPIEntity {
            ^~~~~~~~~~~~~
README.playground:46:16: error: use of undeclared type 'JSONAPIEntity'
struct Person: JSONAPIEntity {
               ^~~~~~~~~~~~~
README.playground:71:16: error: use of undeclared type 'Storable'
struct Author: Storable, Serializable {
               ^~~~~~~~
README.playground:71:26: error: use of undeclared type 'Serializable'
struct Author: Storable, Serializable {
                         ^~~~~~~~~~~~
README.playground:75:26: error: use of undeclared type 'KakapoDB'
    init(id: String, db: KakapoDB) {
                         ^~~~~~~~
README.playground:81:17: error: use of undeclared type 'Storable'
struct Article: Storable, Serializable {
                ^~~~~~~~
README.playground:81:27: error: use of undeclared type 'Serializable'
struct Article: Storable, Serializable {
                          ^~~~~~~~~~~~
README.playground:86:26: error: use of undeclared type 'KakapoDB'
    init(id: String, db: KakapoDB) {
                         ^~~~~~~~
README.playground:8:1: error: value of type 'Parrot' has no member 'serialize'
kakapo.serialize()
^~~~~~ ~~~~~~~~~
README.playground:18:27: error: value of type 'Zoo' has no member 'toData'
let json = NSString(data: zoo.toData()!, encoding: NSUTF8StringEncoding)!
                          ^~~ ~~~~~~
README.playground:38:36: error: value of type 'CustomZoo' has no member 'toData'
let customZooJson = NSString(data: customZoo.toData()!, encoding: NSUTF8StringEncoding)!
                                   ^~~~~~~~~ ~~~~~~
README.playground:53:20: error: use of unresolved identifier 'JSONAPISerializer'
let serializable = JSONAPISerializer(person, topLevelMeta: ["foo": "bar"])
                   ^~~~~~~~~~~~~~~~~
README.playground:57:14: error: use of unresolved identifier 'Router'
let router = Router.register("https://kakapo.com/api/v1")
             ^~~~~~
README.playground:58:42: error: use of undeclared type 'Serializable'
router.get("zoo/:animal") { (request) -> Serializable? in
                                         ^~~~~~~~~~~~
README.playground:69:10: error: use of unresolved identifier 'KakapoDB'
let db = KakapoDB()
         ^~~~~~~~
README.playground:98:39: error: use of undeclared type 'Serializable'
router.get("articles") { (request) -> Serializable? in
                                      ^~~~~~~~~~~~
README.playground:103:50: error: use of undeclared type 'Serializable'
router.get("articles/:author_id") { (request) -> Serializable? in
                                                 ^~~~~~~~~~~~
README.playground:110:39: error: use of undeclared type 'Serializable'
router.post("article") { (request) -> Serializable? in
                                      ^~~~~~~~~~~~
README.playground:32:39: error: value of type '[Parrot]' has no member 'serialize'
        let species = [key("parrot"): parrots.serialize() ?? []]
                                      ^~~~~~~ ~~~~~~~~~

**Comment by MP0w** [comment]
Weird! Looks like it can't find the framework. Did you compile for the iOS simulator? Which arch?

**Comment by perlguy99** [comment]
Yes, compiled for the iOS simulator.

Yep, it was the arch.  I changed the "Debug" setting for "Build Active Architecture Only" to "No" and that fixed it.

I really hate that setting!

Thanks for the quick response and nudge!

**Comment by MP0w** [comment]
Ty, I will check which arch is needed and update the comment ! That settings should be fine but not needed ATM since the compile time is good.
