### ISSUE TITLE
Init entities and relationships

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#12]
Every entity that conform to the protocol (ATM called `KakapoSerializable`) will have to implement `init(id: String)`. To create entities there might be 2 ways:

``` swift
db.create(20, User) //pseudocode
// or
db.create(20) { (id) in
    return User(name: Faker.name, friends: db.findRandom(Friends))
}
```

Friends is a relationship od User:

``` swift
struct Friend: KakapoModel {
    let id: String
    let name: String
    init(id: String) {
       self.id = id
       name = Faker.name
    }
}
```

User will init is relationship as:

``` swift
struct User: KakapoModel {
    let id: String
    let name: String
    let friends: [Friend]
    init(id: String) {
       self.id = id
       name = Faker.name
       friends = 1...(arc4random()).each{ Friend(id: NSUUID()) }
    }
}
```

**Comment by joanromano** [comment]
I think we should aim for usability here. If I want to use this one:

```
db.create(20) { (id) in
    return User(name: Faker.name, friends: db.findRandom(Friends))
}
```

Means that I also need to specify a second init method in user, right? Is that what we want? It also means that I already have to create friend objects (that seems ok). Would we also need to pick different random friends for each user or we don't care about repeating (this is not that important for now, probably)

Also, how about hiding the database implementation details as much as possible? @zzarcon proposed to only use the server for object creation, which will then forward those calls to the internal db. Then the db might only be used in the closure as a passed in parameter.

**Comment by MP0w** [comment]
@joanromano that closure was just an example and should not be required to use it if init(id:) is enough, so we are not forcing to have that init.
I think I Agree with @zzarcon about merging / wrapping the database in the server

**Comment by joanromano** [comment]
But if they need relationships we then force to have two inits

**Comment by MP0w** [comment]
No we don't in User.init(id:) they just have to call Friend.init(id:)

**Comment by joanromano** [comment]
So what is `User(name: Faker.name, friends: db.findRandom(Friends))` then?

**Comment by MP0w** [comment]
Another example using the closure if fake data is not enough (e.g creating a user from ui should have a nane entered by the user)

**Comment by MP0w** [comment]
Reverse and recursive relationships are not part of this discussion see #16

**Comment by MP0w** [comment]
``` swift
struct B: Storable {
    let id: Int

    init(id: Int, db: KakapoDB) {
        self.id = id
    }
}

struct A: Storable {
    let id: Int
    let b: B

    init(id: Int, db: KakapoDB) {
        self.id = id
        self.b = db.create(B)[0]
    }
}
```

**Comment by MP0w** [comment]
or:

``` swift
self.b = sutt.insert { (id) -> B in
     return B(id: id)
}
```
