### ISSUE TITLE
Update APIs to follow swift 3 naming guidelines

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#130]
https://swift.org/blog/swift-3-api-design/
- [x] Update public API (not private for the moment)
- [x] Update example app and playground
- [x] Update README code
- [x] Write changelog with BCHs
- [x] PR
- [ ] Release 2.0.0 📦

**Comment by MP0w** [comment]
Proposal:
- `register(baseURL: String) -> Router`
- `unregister(baseURL: String) -> Router`
- `filter<T: Storable>(_: T.Type, isIncluded: (T) -> Bool) -> [T]` (to align with stdlib)
- `data(includingRelationships: Bool, includingAttributes: Bool, transformingKeys keyTransformer: KeyTransformer?) -> AnyObject?`
- `includedRelationships(includingChildren: Bool, keyTransformer: KeyTransformer?) -> [AnyObject]?`
- `customSerialized(transformingKeys keyTransformer: KeyTransformer?) -> AnyObject?`
- `serialized(transformingKeys keyTransformer: KeyTransformer? = nil) -> AnyObject?`
- `JSONAPISerializer.init(_ object: T, topLevelLinks: [String: JSONAPILink]? = nil, topLevelMeta: Serializable? = nil, includingChildren: Bool = false)`

@joanromano FYI, just a draft

**Comment by MP0w** [comment]
PS: only covering public APIs ATM, you can generate documentation suing jazzy locally on master to check the current public APIs

**Comment by MP0w** [comment]
I would also reintroduce the `key` for `Keytransformer` but I'm not sure if it's possible:

`public typealias KeyTransformer = (_ key: String) -> String`

to 

`public typealias KeyTransformer = (key: String) -> String`

**Comment by joanromano** [comment]
Some thoughts:
- `transformingKeys` in both `serialized` and `customSerialized` don't feel grammatically correct for me
- Not sure about `baseURL` on register/unregister
- KeyTransformer -> Not allowed anymore in function types

**Comment by joanromano** [comment]
And yes, I still find the new naming conventions quite frustrating https://swift.org/documentation/api-design-guidelines/#naming

**Comment by MP0w** [comment]
If we are opinionated we can almost leave it like it is cc/ @zzarcon

**Comment by joanromano** [comment]
May I suggest to just switch `serialized`, `customSerialized` and `filter` ?

**Comment by MP0w** [comment]
Ok but the JSON API stuff might need some labels (some are missing I think)

**Comment by joanromano** [comment]
I like the gerunds when it comes to bool arguments, true.

**Comment by MP0w** [comment]
Actually we could make then non public, except the JSONAPISerializer.init

**Comment by zzarcon** [comment]
I'm afraid of making the public api not opinionated enough
