### ISSUE TITLE
Release PATCH support and backport it 

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#135]
Fix or minor version?

**Comment by MP0w** [comment]
@joanromano do you have time?

**Comment by joanromano** [comment]
Minor IMO

**Comment by joanromano** [comment]
What about #133 ?

**Comment by MP0w** [comment]
👌
@hernangonzalez FYI

**Comment by joanromano** [comment]
btw yup I have time I can do it

**Comment by MP0w** [comment]
#133 still waiting for the PR, you can do it if you still have Xcode 7 and have time or we can just wait

**Comment by joanromano** [comment]
So @MP0w agree with releasing 2.1.0 (Swift 3) and 1.1.1 (Swift 2.3) ?

**Comment by MP0w** [comment]
@joanromano you mean 1.1.0?

**Comment by joanromano** [comment]
Yep sorry @MP0w

**Comment by joanromano** [comment]
2.1.0 is out! 🎉 https://github.com/devlucky/Kakapo/releases/tag/2.1.0

**Comment by joanromano** [comment]
Aaaaaand 1.1.0 is out https://github.com/devlucky/Kakapo/releases/tag/1.1.0
