### ISSUE TITLE
Entities Serialization

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#14]
If something should change or is not clear about it let's discuss it here

Serialization is done by Mirroring the object (reflection) and support for complex serialization like JSONAPI is done using `CustomMirrorType`

**Comment by joanromano** [comment]
I would add more documentation and examples on how to create custom `PropertyPolicy`

**Comment by MP0w** [comment]
Will definitely add doc later, also there is one issue: `serialize`accept Serializable objects so also Arrays and Dictionaries (they privately conform) directly but this isn't suppose to work since their Mirror is quite custom... wondering if I should split the protocols to avoid this.

**Comment by MP0w** [comment]
# TODO:
- [x] Documentation
- [x] Solve recursion entry point that allows Serializable types to be passed even if their mirroring isn't suitable for the serialization
- [x] Entry point for JSONRepresentable
