### ISSUE TITLE
Optimize db insertions

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#17]
DB insertion can get exponentially slow (~90s for 20k entries) because the array that olds the objects is a `Swift.Array` and has to be copied every time we append new objects.
A cool trick for Swift value types is that they are always copied unless uniquely referenced.
That array is hold by a dictionary and to be mutated must be extracted from it and then re-assigned (2 references) making it not uniquely referenced.
To avoid this and use the uniquely referenced trick we can use a box that holds the array:

``` swift
class ArrayBox<T> {
    var array: [T]
}
```

then the dictionary will be of type `[String: ArrayBox<KStorable>]`

And then we can append elements without reference more than once:

`dictionary[someKey].array.appendContentOf(....)`
- [x] Create a performance measure block to avoid regressions
- [x] Document in the code and link to the issue

**Comment by joanromano** [comment]
:hope:

**Comment by MP0w** [comment]
https://travis-ci.org/devlucky/Kakapo/jobs/121879811 5.8seconds
