### ISSUE TITLE
Support id as string

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#26]
should we?

**Comment by MP0w** [comment]
@devlucky/kakapo-core

**Comment by zzarcon** [comment]
Yes, that's why I suggested https://github.com/devlucky/Kakapo.js/issues/24.

And basically allow the user to specify the type of id (we can go with autoincrement as default behaviour)

**Comment by MP0w** [comment]
I would say that `Int` will be the default and `Storable` will use the current implementation (Int). Then We can create a simple protocol `CustomStorable` or `StringStorable` or whatever
that has a default implementation that convert the `Int` to `String` and add a computed property:

``` swift
var id: String {
    get {
       return String(id) // the Int id
    }
}
```

**Comment by MP0w** [comment]
Unfortunately we might need special handling in the `Serializer` to avoid using the `Int` in the JSON so maybe it should be the other way around

**Comment by MP0w** [comment]
@devlucky/swift-core let's discuss before deciding if it should be in the Milestone... looks like we are not sure if we want this (cc/ @zzarcon )
