### ISSUE TITLE
Support Deletion and Overwrite in database

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#31]
Delete and update entities is not supported.
As discussed we won't support:

``` swift
user.delete()
user.save()
```

This would require every entity to hold a database so extra setup for the user.
The idea is to provide:

```
db.delete(entity)
db.save(entity) // or replace/createIfNeeded/.... [discussion]
```

`KakapoDB` will have to find the entity, make sure that is equal (not only the id) to prevent removing another entity and/or using the wrong database. 

If an entity changes and is not saved into db delete will fail because doesn't match the entity in db.

**Comment by MP0w** [comment]
@joanromano please take a look

**Comment by joanromano** [comment]
@MP0w what else do we have appart from the id to compare? Should we make `Serializable` conform to `Comparable`?

**Comment by MP0w** [comment]
@joanromano you mean `Equatable`? Probably... we might have a default implementation of `Equatable` for `Serializable` objects so in most cases you don't need to implement it: Serializable is Equatable when the serialized objects are equal

**Comment by joanromano** [comment]
So our default implementation of `Equatable` for `Serializable` would only compare ids?

**Comment by MP0w** [comment]
Nope, that's not enough to make sure they are the same objects (since you can have multiple dbs the same id can belong to different dbs ).
The default implementation would be to compare the serialized value (the JSON) (probably as NSData?)...

**Comment by joanromano** [comment]
Cool, didn't know we were handling multiple DBs here already. Should we also take into account that two objects from different DBs may have the same id and serialized value?

**Comment by MP0w** [comment]
well then we need to have a db property in the entity... we already support multiple db

**Comment by joanromano** [comment]
@MP0w wondering if we should call it `save` or `update`

**Comment by joanromano** [comment]
@MP0w also, I guess `save`/`complete` should only compare ids?

**Comment by MP0w** [comment]
Yes exactly, I would go for update
