### ISSUE TITLE
Unregister routes

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#34]
Say you register:

``` swift
KakapoServer.get("/user/:id")...
```

We may want to support unregistering routes, this might be automatically done when Server/Routers are deallocated but this can only happen when #23 is done.

@zzarcon alignment needed ?
- [x] Implement #23 
- [x] Test unregister routes
- [x] Test replacing routes
- [x] Test dealloc unregister all routes

**Comment by zzarcon** [comment]
How do you actually deallocate a router?

**Comment by MP0w** [comment]
when it's not used anymore (not strongly referenced anymore):

Let's say you have a ViewController that creates a `Router`, when the VC is gone the Router is deallocated

**Comment by MP0w** [comment]
Alex Manzella [5:34 PM] 
If you have a router only used in some part of the app or for some unit test, ATM The routes are cleared only when you do `KakapoServer.disable` but is not clear that it deletes all the routes (BTW: @joro we need tests for this) and you should/might be able to unregister a single route
