### ISSUE TITLE
Request info refactor

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#35]
``` swift
public struct Request {
    let info: URLInfo
    let HTTPBody: NSData?
}
```

I don't find it easy to use `info.params` and `info.queryParams`.

what about:

``` swift
public struct Request {
    let parameters: [String : String]
    let components: [String : String]
    let HTTPBody: NSData?
    let HTTPHeaders: [String: String]?
}
```

for `/user/:id` then we would have:
components = ["id": "value"]
parameters are the url parameters

@devlucky/js-core ?

**Comment by MP0w** [comment]
related to #21

**Comment by zzarcon** [comment]
I'll prefer instead something like this when declaring a handler like `router.get('/users/:id')` and performing a request like `users/12?page=1&limit=10` with empty headers and body

``` javascript
{
  params: {id: "12"},
  query: {page: "1", limit: "10"},
  headers: {},
  body: {} 
}
```

Also, I don't like the `HTTP` prefix for any of the properties

**Comment by MP0w** [comment]
HTTP prefix is to align with the Foundation counterpart.
Your code is the same except the naming right?
Not sure if params is right because usually what you now called query is called params (that's why I was confused)

**Comment by MP0w** [comment]
Since /id/ is an URL component (`NSURL` call it that way) I was suggesting components, @joanromano ?

**Comment by zzarcon** [comment]
Yes, my suggestion is all about naming, what i call query is usually called query or queryParams. I don't like `components` neither btw.

**Comment by rpunkfu** [comment]
I agree with @zzarcon in terms of naming, since Node.js names it in exactly this way

**Comment by joanromano** [comment]
Since we want to align with Foundation as close as possible, may I suggest using `queryParameters` and `components`? @MP0w

**Comment by MP0w** [comment]
Fine for me
