### ISSUE TITLE
Implement NSURLProtocol.stopLoading() for delayed requests

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#88]
... for routers with latency

**Comment by joanromano** [comment]
Can you expand a bit please?

**Comment by MP0w** [comment]
`NSURLProtocol.stopLoading()` is empty ATM but we can now cancel requests since the router has latency (and does the request asynchronously). anyway I wouldn't do it now, not urgent

**Comment by leviathan** [comment]
@MP0w would that do the trick? - #96
