### ISSUE TITLE
Access request body from route handler

### ISSUE THREAD

**Issue by zzarcon** [devlucky/Kakapo#9]
I think we should we able to provide access to the request body in the request handler:

``` swift
let server = KakapoServer()

server.get("/user", (request) {
  return request.body
}

```

**Comment by MP0w** [comment]
I don't get it

**Comment by MP0w** [comment]
@zzarcon ping

**Comment by zzarcon** [comment]
@MP0w sorry for the delay, basically I think we should provide a way to access to the request body in the `request hadnler` - http://www.w3schools.com/tags/ref_httpmethods.asp

Usually when you define a **post** handler, you want to create something in your db. In order to know what to create you have to inspect the request body. Abstract example:

``` javascript
let server = Server();

server.post('/users', (request, db) => {
  //Imagine the body is parsed somehow
  let user = request.body.user;

  db.create(User, {
    id: user.id,
    firstName: user.first_name
  });
});

```

**Comment by zzarcon** [comment]
testing gh integration

**Comment by joanromano** [comment]
@zzarcon @MP0w I thought we said the client _doesn't_ have access to db externally, but we rather build a facade from the server around it

**Comment by zzarcon** [comment]
Yeah, sorry, we can just return the server there

**Comment by joanromano** [comment]
But that would be pointless, the client has already an instance to it

**Comment by MP0w** [comment]
Ah got it now, yes NSURLRequest must be passed
