### ISSUE TITLE
Allow wildcard in baseURL

### ISSUE THREAD

**Issue by MP0w** [devlucky/Kakapo#90]
just for the future... Consider it, not sure we want to do it.

**Comment by leviathan** [comment]
Why would that be needed?
I don't see the use-case for wildcards in the base-url.

```
let routerA = Router.register("http://www.test.com")
let routerB = Router.register("http://www.somefunkydomain.com")

session.dataTaskWithURL(NSURL(string: "http://*.com/users/1")!) { (data, _, _) in
  // ->> would return all "users" registered across the two previously registered baseURLs
}.resume()
```

Would that be your use-case?
Using a "wildcard" character to fetch a certain set of entities across different registered URLs.

**Comment by MP0w** [comment]
@leviathan hey! Thanks for sharing your opinion!
I actually agree the usefulness would be limited, I just opened the issue while refactoring that part to discuss .
The wildcard would be something different, the baseURL can be a part of the URL that will be in common for every registered route:
E.g
Http://domain.com/api/user/:id/friends
Http://domain.com/api/user/:id/Whatever/:anotherwildcard

In those case "id" is a wildcard but ATM can't be part of baseURL, so you need to register the Router with Http://domain.com/api/user/ or Http://domain.com/api/

Being able to register routers with wildcard would allow you to use: Http://domain.com/api/user/:id/ (and share the same router)

However this would make the matching more complex (not to much but ATM is just the key of a dictionary) so I'm more into leaving it like it is. What do you think?
