### ISSUE TITLE
Rename KakapoDB and KakapoServer

### ISSUE THREAD

**Issue by joanromano** [devlucky/Kakapo#98]
My thoughts on this:
- We should rename them to `Store` and `Server`, Kakapo prefixes don't make sense with Swift modules as we know.
- This shouldn't mean a BCH but I guess we can't avoid it. Still, I think having to release 1.0 just because of this is way too much.

**Comment by leviathan** [comment]
Yeah, the `Server` name is kind of confusing. Its more like a request interceptor or such

**Comment by MP0w** [comment]
@joanromano we should do it before releasing the support for Swift 2.3 and 3.0 otherwise we need to raise the version again

**Comment by joanromano** [comment]
Absolutely @MP0w
